stages:
  - deploy

pages:
  stage: deploy
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # If there are any install/build steps, do them before the copy
    - mv current/* archive
    - mv archive public
  artifacts:
    paths:
      - public
