stages:
  - deploy

pages:
  image: node:22-alpine3.19
  stage: deploy
  environment: production
  # rules:
  #   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # If there are any install/build steps, do them before the copy
    - cd current
    - echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL" >> .env
    - echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY" >> .env
    - npm install
    - npm run build
    - cd ..
    - mv current/dist/* archive
    - mv archive public
  artifacts:
    paths:
      - public
